---
version: "3"
services:
  unbound:
    container_name: unbound
    image: d3vilh/unbound-docker:latest
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
