---
version: "3"
services:
  unbound:
    container_name: unbound
    image: local/unbound:latest
    ports:
      - "53:5335/tcp"
      - "53:5335/udp"
    volumes:
      - "./etc-unbound/unbound.conf:/etc/unbound/unbound.conf"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
